spring:
  redis:
    host: localhost
    port: 6379
    password:
    #  使用那个库，默认是使用0库
    #  database: 0
    timeout: 6000  # 连接超时时长（毫秒）
    lettuce:
      pool:
        max-active: 128  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 10000ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
server:
  port: 9999